// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: proto/danmakucache/danmaku-cache.proto

package danmakucache

import (
	common "github.com/bit-danmaku/danmaku/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelID uint64 `protobuf:"varint,2,opt,name=ChannelID,proto3" json:"ChannelID,omitempty"`
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_danmakucache_danmaku_cache_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_danmakucache_danmaku_cache_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_proto_danmakucache_danmaku_cache_proto_rawDescGZIP(), []int{0}
}

func (x *CallRequest) GetChannelID() uint64 {
	if x != nil {
		return x.ChannelID
	}
	return 0
}

type CallResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DanmakuList []*common.Danmaku `protobuf:"bytes,1,rep,name=DanmakuList,proto3" json:"DanmakuList,omitempty"`
}

func (x *CallResponse) Reset() {
	*x = CallResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_danmakucache_danmaku_cache_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallResponse) ProtoMessage() {}

func (x *CallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_danmakucache_danmaku_cache_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallResponse.ProtoReflect.Descriptor instead.
func (*CallResponse) Descriptor() ([]byte, []int) {
	return file_proto_danmakucache_danmaku_cache_proto_rawDescGZIP(), []int{1}
}

func (x *CallResponse) GetDanmakuList() []*common.Danmaku {
	if x != nil {
		return x.DanmakuList
	}
	return nil
}

var File_proto_danmakucache_danmaku_cache_proto protoreflect.FileDescriptor

var file_proto_danmakucache_danmaku_cache_proto_rawDesc = []byte{
	0x0a, 0x26, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x61, 0x6e, 0x6d, 0x61, 0x6b, 0x75, 0x63,
	0x61, 0x63, 0x68, 0x65, 0x2f, 0x64, 0x61, 0x6e, 0x6d, 0x61, 0x6b, 0x75, 0x2d, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x64, 0x61, 0x6e, 0x6d, 0x61, 0x6b,
	0x75, 0x63, 0x61, 0x63, 0x68, 0x65, 0x1a, 0x14, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x64,
	0x61, 0x6e, 0x6d, 0x61, 0x6b, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2b, 0x0a, 0x0b,
	0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x44, 0x22, 0x41, 0x0a, 0x0c, 0x43, 0x61, 0x6c,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x0b, 0x44, 0x61, 0x6e,
	0x6d, 0x61, 0x6b, 0x75, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x44, 0x61, 0x6e, 0x6d, 0x61, 0x6b, 0x75, 0x52,
	0x0b, 0x44, 0x61, 0x6e, 0x6d, 0x61, 0x6b, 0x75, 0x4c, 0x69, 0x73, 0x74, 0x32, 0x62, 0x0a, 0x0c,
	0x44, 0x61, 0x6e, 0x6d, 0x61, 0x6b, 0x75, 0x43, 0x61, 0x63, 0x68, 0x65, 0x12, 0x52, 0x0a, 0x17,
	0x47, 0x65, 0x74, 0x44, 0x61, 0x6e, 0x6d, 0x61, 0x6b, 0x75, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x19, 0x2e, 0x64, 0x61, 0x6e, 0x6d, 0x61, 0x6b,
	0x75, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x64, 0x61, 0x6e, 0x6d, 0x61, 0x6b, 0x75, 0x63, 0x61, 0x63, 0x68,
	0x65, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x3b, 0x64, 0x61, 0x6e, 0x6d, 0x61, 0x6b, 0x75, 0x63, 0x61,
	0x63, 0x68, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_danmakucache_danmaku_cache_proto_rawDescOnce sync.Once
	file_proto_danmakucache_danmaku_cache_proto_rawDescData = file_proto_danmakucache_danmaku_cache_proto_rawDesc
)

func file_proto_danmakucache_danmaku_cache_proto_rawDescGZIP() []byte {
	file_proto_danmakucache_danmaku_cache_proto_rawDescOnce.Do(func() {
		file_proto_danmakucache_danmaku_cache_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_danmakucache_danmaku_cache_proto_rawDescData)
	})
	return file_proto_danmakucache_danmaku_cache_proto_rawDescData
}

var file_proto_danmakucache_danmaku_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_danmakucache_danmaku_cache_proto_goTypes = []interface{}{
	(*CallRequest)(nil),    // 0: danmakucache.CallRequest
	(*CallResponse)(nil),   // 1: danmakucache.CallResponse
	(*common.Danmaku)(nil), // 2: common.Danmaku
}
var file_proto_danmakucache_danmaku_cache_proto_depIdxs = []int32{
	2, // 0: danmakucache.CallResponse.DanmakuList:type_name -> common.Danmaku
	0, // 1: danmakucache.DanmakuCache.GetDanmakuListByChannel:input_type -> danmakucache.CallRequest
	1, // 2: danmakucache.DanmakuCache.GetDanmakuListByChannel:output_type -> danmakucache.CallResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_danmakucache_danmaku_cache_proto_init() }
func file_proto_danmakucache_danmaku_cache_proto_init() {
	if File_proto_danmakucache_danmaku_cache_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_danmakucache_danmaku_cache_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_danmakucache_danmaku_cache_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_danmakucache_danmaku_cache_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_danmakucache_danmaku_cache_proto_goTypes,
		DependencyIndexes: file_proto_danmakucache_danmaku_cache_proto_depIdxs,
		MessageInfos:      file_proto_danmakucache_danmaku_cache_proto_msgTypes,
	}.Build()
	File_proto_danmakucache_danmaku_cache_proto = out.File
	file_proto_danmakucache_danmaku_cache_proto_rawDesc = nil
	file_proto_danmakucache_danmaku_cache_proto_goTypes = nil
	file_proto_danmakucache_danmaku_cache_proto_depIdxs = nil
}
