// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: proto/danmakucache/danmaku-cache.proto

package danmakucache

import (
	common "github.com/bit-danmaku/danmaku/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelID uint64 `protobuf:"varint,1,opt,name=ChannelID,proto3" json:"ChannelID,omitempty"`
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_danmakucache_danmaku_cache_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_danmakucache_danmaku_cache_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_danmakucache_danmaku_cache_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetChannelID() uint64 {
	if x != nil {
		return x.ChannelID
	}
	return 0
}

type GetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DanmakuList []*common.Danmaku `protobuf:"bytes,1,rep,name=DanmakuList,proto3" json:"DanmakuList,omitempty"`
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_danmakucache_danmaku_cache_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_danmakucache_danmaku_cache_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_danmakucache_danmaku_cache_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetDanmakuList() []*common.Danmaku {
	if x != nil {
		return x.DanmakuList
	}
	return nil
}

type PostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelID uint64          `protobuf:"varint,1,opt,name=ChannelID,proto3" json:"ChannelID,omitempty"`
	Danmaku   *common.Danmaku `protobuf:"bytes,2,opt,name=Danmaku,proto3" json:"Danmaku,omitempty"`
}

func (x *PostRequest) Reset() {
	*x = PostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_danmakucache_danmaku_cache_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostRequest) ProtoMessage() {}

func (x *PostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_danmakucache_danmaku_cache_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostRequest.ProtoReflect.Descriptor instead.
func (*PostRequest) Descriptor() ([]byte, []int) {
	return file_proto_danmakucache_danmaku_cache_proto_rawDescGZIP(), []int{2}
}

func (x *PostRequest) GetChannelID() uint64 {
	if x != nil {
		return x.ChannelID
	}
	return 0
}

func (x *PostRequest) GetDanmaku() *common.Danmaku {
	if x != nil {
		return x.Danmaku
	}
	return nil
}

type PostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code uint64 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *PostResponse) Reset() {
	*x = PostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_danmakucache_danmaku_cache_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostResponse) ProtoMessage() {}

func (x *PostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_danmakucache_danmaku_cache_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostResponse.ProtoReflect.Descriptor instead.
func (*PostResponse) Descriptor() ([]byte, []int) {
	return file_proto_danmakucache_danmaku_cache_proto_rawDescGZIP(), []int{3}
}

func (x *PostResponse) GetCode() uint64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PostResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_proto_danmakucache_danmaku_cache_proto protoreflect.FileDescriptor

var file_proto_danmakucache_danmaku_cache_proto_rawDesc = []byte{
	0x0a, 0x26, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x61, 0x6e, 0x6d, 0x61, 0x6b, 0x75, 0x63,
	0x61, 0x63, 0x68, 0x65, 0x2f, 0x64, 0x61, 0x6e, 0x6d, 0x61, 0x6b, 0x75, 0x2d, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x64, 0x61, 0x6e, 0x6d, 0x61, 0x6b,
	0x75, 0x63, 0x61, 0x63, 0x68, 0x65, 0x1a, 0x14, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x64,
	0x61, 0x6e, 0x6d, 0x61, 0x6b, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x0a,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x44, 0x22, 0x40, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x0b, 0x44, 0x61, 0x6e, 0x6d, 0x61,
	0x6b, 0x75, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x44, 0x61, 0x6e, 0x6d, 0x61, 0x6b, 0x75, 0x52, 0x0b, 0x44,
	0x61, 0x6e, 0x6d, 0x61, 0x6b, 0x75, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x56, 0x0a, 0x0b, 0x50, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x44, 0x12, 0x29, 0x0a, 0x07, 0x44, 0x61, 0x6e, 0x6d, 0x61,
	0x6b, 0x75, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x44, 0x61, 0x6e, 0x6d, 0x61, 0x6b, 0x75, 0x52, 0x07, 0x44, 0x61, 0x6e, 0x6d, 0x61,
	0x6b, 0x75, 0x22, 0x34, 0x0a, 0x0c, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0xa8, 0x01, 0x0a, 0x0c, 0x44, 0x61, 0x6e,
	0x6d, 0x61, 0x6b, 0x75, 0x43, 0x61, 0x63, 0x68, 0x65, 0x12, 0x46, 0x0a, 0x0b, 0x50, 0x6f, 0x73,
	0x74, 0x44, 0x61, 0x6e, 0x6d, 0x61, 0x6b, 0x75, 0x12, 0x19, 0x2e, 0x64, 0x61, 0x6e, 0x6d, 0x61,
	0x6b, 0x75, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x64, 0x61, 0x6e, 0x6d, 0x61, 0x6b, 0x75, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x50, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x44, 0x61, 0x6e, 0x6d, 0x61, 0x6b, 0x75, 0x4c,
	0x69, 0x73, 0x74, 0x42, 0x79, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x18, 0x2e, 0x64,
	0x61, 0x6e, 0x6d, 0x61, 0x6b, 0x75, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x64, 0x61, 0x6e, 0x6d, 0x61, 0x6b, 0x75,
	0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x3b, 0x64, 0x61, 0x6e, 0x6d, 0x61, 0x6b,
	0x75, 0x63, 0x61, 0x63, 0x68, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_danmakucache_danmaku_cache_proto_rawDescOnce sync.Once
	file_proto_danmakucache_danmaku_cache_proto_rawDescData = file_proto_danmakucache_danmaku_cache_proto_rawDesc
)

func file_proto_danmakucache_danmaku_cache_proto_rawDescGZIP() []byte {
	file_proto_danmakucache_danmaku_cache_proto_rawDescOnce.Do(func() {
		file_proto_danmakucache_danmaku_cache_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_danmakucache_danmaku_cache_proto_rawDescData)
	})
	return file_proto_danmakucache_danmaku_cache_proto_rawDescData
}

var file_proto_danmakucache_danmaku_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_danmakucache_danmaku_cache_proto_goTypes = []interface{}{
	(*GetRequest)(nil),     // 0: danmakucache.GetRequest
	(*GetResponse)(nil),    // 1: danmakucache.GetResponse
	(*PostRequest)(nil),    // 2: danmakucache.PostRequest
	(*PostResponse)(nil),   // 3: danmakucache.PostResponse
	(*common.Danmaku)(nil), // 4: common.Danmaku
}
var file_proto_danmakucache_danmaku_cache_proto_depIdxs = []int32{
	4, // 0: danmakucache.GetResponse.DanmakuList:type_name -> common.Danmaku
	4, // 1: danmakucache.PostRequest.Danmaku:type_name -> common.Danmaku
	2, // 2: danmakucache.DanmakuCache.PostDanmaku:input_type -> danmakucache.PostRequest
	0, // 3: danmakucache.DanmakuCache.GetDanmakuListByChannel:input_type -> danmakucache.GetRequest
	3, // 4: danmakucache.DanmakuCache.PostDanmaku:output_type -> danmakucache.PostResponse
	1, // 5: danmakucache.DanmakuCache.GetDanmakuListByChannel:output_type -> danmakucache.GetResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_danmakucache_danmaku_cache_proto_init() }
func file_proto_danmakucache_danmaku_cache_proto_init() {
	if File_proto_danmakucache_danmaku_cache_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_danmakucache_danmaku_cache_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_danmakucache_danmaku_cache_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_danmakucache_danmaku_cache_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_danmakucache_danmaku_cache_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_danmakucache_danmaku_cache_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_danmakucache_danmaku_cache_proto_goTypes,
		DependencyIndexes: file_proto_danmakucache_danmaku_cache_proto_depIdxs,
		MessageInfos:      file_proto_danmakucache_danmaku_cache_proto_msgTypes,
	}.Build()
	File_proto_danmakucache_danmaku_cache_proto = out.File
	file_proto_danmakucache_danmaku_cache_proto_rawDesc = nil
	file_proto_danmakucache_danmaku_cache_proto_goTypes = nil
	file_proto_danmakucache_danmaku_cache_proto_depIdxs = nil
}
