// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: kafkaconsumer/kafka-consumer.proto

package kafkaconsumer

import (
	common "github.com/bit-danmaku/danmaku/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelID uint64          `protobuf:"varint,1,opt,name=ChannelID,json=channelID,proto3" json:"ChannelID,omitempty"`
	Danmaku   *common.Danmaku `protobuf:"bytes,2,opt,name=Danmaku,json=danmaku,proto3" json:"Danmaku,omitempty"`
}

func (x *PostRequest) Reset() {
	*x = PostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kafkaconsumer_kafka_consumer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostRequest) ProtoMessage() {}

func (x *PostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kafkaconsumer_kafka_consumer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostRequest.ProtoReflect.Descriptor instead.
func (*PostRequest) Descriptor() ([]byte, []int) {
	return file_kafkaconsumer_kafka_consumer_proto_rawDescGZIP(), []int{0}
}

func (x *PostRequest) GetChannelID() uint64 {
	if x != nil {
		return x.ChannelID
	}
	return 0
}

func (x *PostRequest) GetDanmaku() *common.Danmaku {
	if x != nil {
		return x.Danmaku
	}
	return nil
}

type PostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code uint64 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *PostResponse) Reset() {
	*x = PostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kafkaconsumer_kafka_consumer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostResponse) ProtoMessage() {}

func (x *PostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kafkaconsumer_kafka_consumer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostResponse.ProtoReflect.Descriptor instead.
func (*PostResponse) Descriptor() ([]byte, []int) {
	return file_kafkaconsumer_kafka_consumer_proto_rawDescGZIP(), []int{1}
}

func (x *PostResponse) GetCode() uint64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PostResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_kafkaconsumer_kafka_consumer_proto protoreflect.FileDescriptor

var file_kafkaconsumer_kafka_consumer_proto_rawDesc = []byte{
	0x0a, 0x22, 0x6b, 0x61, 0x66, 0x6b, 0x61, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x2f,
	0x6b, 0x61, 0x66, 0x6b, 0x61, 0x2d, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6b, 0x61, 0x66, 0x6b, 0x61, 0x63, 0x6f, 0x6e, 0x73, 0x75,
	0x6d, 0x65, 0x72, 0x1a, 0x14, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x64, 0x61, 0x6e, 0x6d,
	0x61, 0x6b, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x56, 0x0a, 0x0b, 0x50, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x44, 0x12, 0x29, 0x0a, 0x07, 0x44, 0x61, 0x6e, 0x6d, 0x61, 0x6b,
	0x75, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x44, 0x61, 0x6e, 0x6d, 0x61, 0x6b, 0x75, 0x52, 0x07, 0x64, 0x61, 0x6e, 0x6d, 0x61, 0x6b,
	0x75, 0x22, 0x34, 0x0a, 0x0c, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x59, 0x0a, 0x0d, 0x4b, 0x61, 0x66, 0x6b, 0x61,
	0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x12, 0x48, 0x0a, 0x0b, 0x50, 0x6f, 0x73, 0x74,
	0x44, 0x61, 0x6e, 0x6d, 0x61, 0x6b, 0x75, 0x12, 0x1a, 0x2e, 0x6b, 0x61, 0x66, 0x6b, 0x61, 0x63,
	0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6b, 0x61, 0x66, 0x6b, 0x61, 0x63, 0x6f, 0x6e, 0x73, 0x75,
	0x6d, 0x65, 0x72, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2f, 0x3b, 0x6b, 0x61, 0x66, 0x6b, 0x61, 0x63, 0x6f,
	0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kafkaconsumer_kafka_consumer_proto_rawDescOnce sync.Once
	file_kafkaconsumer_kafka_consumer_proto_rawDescData = file_kafkaconsumer_kafka_consumer_proto_rawDesc
)

func file_kafkaconsumer_kafka_consumer_proto_rawDescGZIP() []byte {
	file_kafkaconsumer_kafka_consumer_proto_rawDescOnce.Do(func() {
		file_kafkaconsumer_kafka_consumer_proto_rawDescData = protoimpl.X.CompressGZIP(file_kafkaconsumer_kafka_consumer_proto_rawDescData)
	})
	return file_kafkaconsumer_kafka_consumer_proto_rawDescData
}

var file_kafkaconsumer_kafka_consumer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kafkaconsumer_kafka_consumer_proto_goTypes = []interface{}{
	(*PostRequest)(nil),    // 0: kafkaconsumer.PostRequest
	(*PostResponse)(nil),   // 1: kafkaconsumer.PostResponse
	(*common.Danmaku)(nil), // 2: common.Danmaku
}
var file_kafkaconsumer_kafka_consumer_proto_depIdxs = []int32{
	2, // 0: kafkaconsumer.PostRequest.Danmaku:type_name -> common.Danmaku
	0, // 1: kafkaconsumer.KafkaConsumer.PostDanmaku:input_type -> kafkaconsumer.PostRequest
	1, // 2: kafkaconsumer.KafkaConsumer.PostDanmaku:output_type -> kafkaconsumer.PostResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kafkaconsumer_kafka_consumer_proto_init() }
func file_kafkaconsumer_kafka_consumer_proto_init() {
	if File_kafkaconsumer_kafka_consumer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kafkaconsumer_kafka_consumer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kafkaconsumer_kafka_consumer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kafkaconsumer_kafka_consumer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kafkaconsumer_kafka_consumer_proto_goTypes,
		DependencyIndexes: file_kafkaconsumer_kafka_consumer_proto_depIdxs,
		MessageInfos:      file_kafkaconsumer_kafka_consumer_proto_msgTypes,
	}.Build()
	File_kafkaconsumer_kafka_consumer_proto = out.File
	file_kafkaconsumer_kafka_consumer_proto_rawDesc = nil
	file_kafkaconsumer_kafka_consumer_proto_goTypes = nil
	file_kafkaconsumer_kafka_consumer_proto_depIdxs = nil
}
