version: "3.7"
services:
  frontend:
    image: fkynjyq/bit-danmaku_frontend
    ports:
      - 8081:80

  old-danmaku:
    image: fkynjyq/bit-danmaku_old-danmaku
    ports:
      - 8009:8080
    depends_on:
      - mariadb
    restart: always

  api-gateway:
    image: fkynjyq/bit-danmaku_api-gateway
    restart: always
    ports:
      - 8008:8080

  danmaku-cache:
    image: fkynjyq/bit-danmaku_danmaku-cache
    depends_on:
      - mariadb
      - redis
    restart: always
    deploy:
      replicas: 3

  # For test use.
  #test:
    #image: nginx
    #volumes:
      #- ./bin/:/app/
    #entrypoint:
      #- bash
      #- -c
      #- "sleep 10000"
    #environment:
      #- MICRO_BROKER=kafka
      #- MICRO_BROKER_ADDRESS=kafka:9092

  
  kafka-producer:
    image: fkynjyq/bit-danmaku_kafka-producer
    depends_on:
      - kafka
    restart: always
    deploy:
      replicas: 3

    environment:
      - MICRO_BROKER=kafka
      - MICRO_BROKER_ADDRESS=kafka:9092

  kafka-consumer:
    image: fkynjyq/bit-danmaku_kafka-consumer
    depends_on:
      - mariadb
      - redis
      - kafka
    restart: always
    environment:
      - MICRO_BROKER=kafka
      - MICRO_BROKER_ADDRESS=kafka:9092

  mariadb:
    image: mariadb
    restart: always
    #ports:
      #- 3306:3306
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MARIADB_DATABASE: olddanmaku
    #command: "mysqld --init-file /data/application/init.sql"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 7999:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb

  redis:
    image: redis

  redis-commander:
    image: rediscommander/redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 7998:8081

  zookeeper:
    image: wurstmeister/zookeeper
  
  kafka:
    image: wurstmeister/kafka:latest
    restart: always
    environment:
      - MDNS_HOSTNAME=kafka.kafka.local
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENERS=PLAINTEXT://:9092
    #ports:
      #- 9092:9092


volumes:
  mariadb-data:
