version: "3.7"
services:
  frontend:
    image: fkynjhq/bit-danmaku_frontend
    ports:
      - 8080:80

  api-gateway:
    image: fkynjyq/bit-danmaku_api-gateway
    ports:
      - 8008:8080

  danmaku-cache:
    image: fkynjyq/bit-danmaku_danmaku-cache

  #test:
    #image: nginx
    #volumes:
      #- ./bin/:/app/
    #entrypoint:
      #- bash
      #- -c
      #- "sleep 10000"
    #environment:
      #- MICRO_BROKER=kafka
      #- MICRO_BROKER_ADDRESS=kafka:9092

  
  kafka-producer:
    #build:
      #context: .
      #args:
        #- BIN_NAME=kafka-producer
    image: fkynjyq/bit-danmaku_kafka-producer

    environment:
      - MICRO_BROKER=kafka
      - MICRO_BROKER_ADDRESS=kafka:9092

  kafka-consumer:
    #build:
      #context: .
      #args:
        #- BIN_NAME=kafka-consumer
    image: fkynjyq/bit-danmaku_kafka-consumer

    environment:
      - MICRO_BROKER=kafka
      - MICRO_BROKER_ADDRESS=kafka:9092

  mariadb:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
    #command: "mysqld --init-file /data/application/init.sql"
    #volumes:
    #- ./init.sql:/data/application/init.sql
    # hello

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 7999:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb

  redis:
    image: redis
    ports:
      - 6379:6379

  redis-commander:
    image: rediscommander/redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 7998:8081

  zookeeper:
    image: wurstmeister/zookeeper
  
  kafka:
    image: hausgold/kafka:latest
    environment:
      - MDNS_HOSTNAME=kafka.kafka.local
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENERS=PLAINTEXT://:9092
    ports:
      - 9092:9092

  kafka-exporter:
    image: danielqsj/kafka-exporter
    ports:
      - 9308:9308


volumes:
  mariadb-data:
