name: devops

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bin: [api-gateway, danmaku-cache, kafka-producer]
    steps:
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: fkynjyq/bit-danmaku_${{ matrix.bin }}:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.MYTOKEN }}
          build-args: |
            BIN_NAME=${{ matrix.bin }}
